version: 1.0.{build}
build:
  verbosity: minimal
  
test:
  # only assemblies to test
  assemblies:
    only:
      - "C:\projects\namesorter\NameSorter.Library.Test\bin\Debug\NameSorter.Library.Test.dll"
