version: 1.0.{build}
build:
  verbosity: minimal
  
test:
  # only assemblies to test
  assemblies:
    only:
      - 'NameSorter.Library.Test\bin\Debug\NameSorter.Library.Test.dll'

test_script:
- vstest.console /logger:Appveyor "NameSorter.Library.Test\bin\debug\NameSorter.Library.Test.dll" /UseVsixExtensions:true
